export const easternTimezoneOptions = [
  { label: "UTC+01:00", value: "Etc/GMT-1" },
  { label: "UTC+02:00", value: "Etc/GMT-2" },
  { label: "UTC+03:00", value: "Etc/GMT-3" },
  { label: "UTC+03:30", value: "Iran" },
  { label: "UTC+04:00", value: "Etc/GMT-4" },
  { label: "UTC+04:30", value: "Asia/Kabul" },
  { label: "UTC+05:00", value: "Etc/GMT-5" },
  { label: "UTC+05:30", value: "Asia/Calcutta" },
  { label: "UTC+05:45", value: "Asia/Katmandu" },
  { label: "UTC+06:00", value: "Etc/GMT-6" },
  { label: "UTC+06:30", value: "Asia/Rangoon" },
  { label: "UTC+07:00", value: "Etc/GMT-7" },
  { label: "UTC+08:00", value: "Etc/GMT-8" },
  { label: "UTC+08:45", value: "Australia/Eucla" },
  { label: "UTC+09:00", value: "Etc/GMT-9" },
  { label: "UTC+09:30", value: "Australia/Adelaide" },
  { label: "UTC+10:00", value: "Etc/GMT-10" },
  { label: "UTC+10:30", value: "Australia/Lord_Howe" },
  { label: "UTC+11:00", value: "Etc/GMT-11" },
  { label: "UTC+12:00", value: "Etc/GMT-12" },
  { label: "UTC+12:45", value: "Pacific/Chatham" },
  { label: "UTC+13:00", value: "Pacific/Tongatapu" },
  { label: "UTC+14:00", value: "Pacific/Kiritimati" },
];

export const westernTimezoneOptions = [
  { label: "UTC-12:00", value: "Etc/GMT+12" },
  { label: "UTC-11:00", value: "Etc/GMT+11" },
  { label: "UTC-10:00", value: "Etc/GMT+10" },
  { label: "UTC-09:30", value: "Pacific/Marquesas" },
  { label: "UTC-09:00", value: "Etc/GMT+9" },
  { label: "UTC-08:00", value: "Etc/GMT+8" },
  { label: "UTC-07:00", value: "Etc/GMT+7" },
  { label: "UTC-06:00", value: "Etc/GMT+6" },
  { label: "UTC-05:00", value: "Etc/GMT+5" },
  { label: "UTC-04:00", value: "Etc/GMT+4" },
  { label: "UTC-03:30", value: "Canada/Newfoundland" },
  { label: "UTC-03:00", value: "Etc/GMT+3" },
  { label: "UTC-02:00", value: "Etc/GMT+2" },
  { label: "UTC-01:00", value: "Etc/GMT+1" },
  { label: "UTC+00:00", value: "Etc/GMT" },
];

export const responsesList = ["hey", "hi", "hello", "howdy", "what's up,", "bonjour"];